logging:
  level:
    # Enabling trace for app specific logging.
    com.tvajjala: INFO
    org.springframework: INFO
    com.github: debug

wiremock:
  port: 8084 # mock ServerPort

spring:
  output:
    ansi:
      enabled: always

